---
title: "Nonlinear"
author: "JunLu"
date: "4/1/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE
                      )
library(caret)
theme1 <- trellis.par.get()
theme1$plot.symbol$col <- rgb(.2, .4, .2, .2) 
theme1$plot.symbol$pch <- 16
theme1$plot.line$col <- rgb(.8, .1, .1, 1) 
theme1$plot.line$lwd <- 2
theme1$strip.background$col <- rgb(.0, .2, .6, .2)
trellis.par.set(theme1)

library(tidyverse)
library(caret)
library(splines)
library(gam)
library(mgcv)
library(boot)
library(pdp)
library(earth)
```


## Import the train dataset

```{r}
train = read_csv("./non-linear/train.csv")

y = train$transformed_value

x = model.matrix(transformed_value ~ ., train)[,-1] 
```

## Set a random seed

```{r}
set.seed(1)
```


## Generallized additive model (GAM)

### Use caret package
```{r, echo=FALSE}
ctrl1 <- trainControl(method = "cv", number = 10)
gam.fit = train(x, y,
                method = "gam",
                tuneGrid = data.frame(method = "GCV.Cp", 
                                      select = c(TRUE,FALSE)), 
                trControl = ctrl1)

save(gam.fit, file = "./gam_fit.rda")
```

```{r}
load(file = "./gam_fit.rda")
gam.fit$bestTune
gam.fit$finalModel
```

```{r, echo=FALSE}
gam = gam( transformed_value ~ nationality + s(positioning) + 
    s(marking) + s(sliding_tackle) + s(standing_tackle) + s(finishing) + 
    s(volleys) + s(age) + s(crossing) + s(dribbling) + s(interceptions) + 
    s(free_kick_accuracy) + s(long_shots) + s(heading_accuracy) + 
    s(curve) + s(stamina) + s(aggression) + s(ball_control) + 
    s(potential) + s(penalties) + s(gk_handling) + s(short_passing) + 
    s(gk_diving) + s(gk_reflexes) + s(gk_kicking) + s(gk_positioning) + 
    s(shot_power) + s(long_passing) + s(acceleration) + s(sprint_speed) + 
    s(balance) + s(agility) + s(reactions) + s(strength) + s(jumping) + 
    s(composure) + s(vision) + s(special), data = train)

save(gam, file = "./gam.rda")
```

```{r}
load(file = "./gam.rda")
par(mfrow = c(1,4)) 
plot(gam)
```





## Multivariate Adaptive Regression Splines (MARS)

```{r, echo=FALSE}
ctrl1 <- trainControl(method = "cv", number = 10)
mars_grid = expand.grid(degree = 1:2,
                        nprune = 2:38)
mars.fit = train(x, y,
                 method = "earth",
                 tuneGrid = mars_grid,
                 trControl = ctrl1
                 )
save(mars.fit, file = "./mars.rda")
```

```{r}
load(file = "./mars.rda")

summary(mars.fit)
mars.fit$bestTune
```




```{r}
p1 = partial(mars.fit, pred.var =c("age"), grid.resolution = 10) %>% autoplot()
p2 = partial(mars.fit, pred.var =c("potential"), grid.resolution = 10) %>% autoplot()
p3 = partial(mars.fit, pred.var =c("special"), grid.resolution = 10) %>% autoplot()
p4 = partial(mars.fit, pred.var =c("balance"), grid.resolution = 10) %>% autoplot()
p5 = partial(mars.fit, pred.var =c("gk_diving"), grid.resolution = 10) %>% autoplot()
p6 = partial(mars.fit, pred.var =c("gk_handling"), grid.resolution = 10) %>% autoplot()
p7 = partial(mars.fit, pred.var =c("gk_kicking"), grid.resolution = 10) %>% autoplot()
p8 = partial(mars.fit, pred.var =c("gk_positioning"), grid.resolution = 10) %>% autoplot()
p9 = partial(mars.fit, pred.var =c("gk_reflexes"), grid.resolution = 10) %>% autoplot()
p10 = partial(mars.fit, pred.var =c("reactions"), grid.resolution = 10) %>% autoplot()
p11 = partial(mars.fit, pred.var =c("strength"), grid.resolution = 10) %>% autoplot()
p12 = partial(mars.fit, pred.var =c("vision"), grid.resolution = 10) %>% autoplot()

grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, ncol = 3, nrow = 4)
```


## Compare those models
```{r}
bwplot(resamples(list(mars = mars.fit,gam = gam.fit)), 
       metric = "RMSE")
```


## Importance
```{r}
varImp(mars.fit)
varImp(gam.fit)
```














### Set the model by exploratory analysis
```{r, echo=FALSE}
gam.m1 = gam(transformed_value ~ age + nationality + potential + special + acceleration 
             + aggression + agility + balance + ball_control + composure + crossing + curve + 
                 dribbling + finishing + free_kick_accuracy + gk_diving + gk_handling + gk_kicking +
                 gk_positioning + gk_reflexes + heading_accuracy + interceptions +
                 jumping + long_passing + long_shots + marking + penalties + positioning +
                 reactions + short_passing + shot_power + sliding_tackle + sprint_speed + stamina +
                 standing_tackle + strength + vision + volleys, data = train)

gam.m2 = gam(transformed_value ~ s(age) + nationality  + potential + special + acceleration 
             + aggression + agility + balance + ball_control + composure + crossing + curve + 
                 dribbling + finishing + free_kick_accuracy + gk_diving + gk_handling + gk_kicking +
                 gk_positioning + gk_reflexes + heading_accuracy + interceptions +
                 jumping + long_passing + long_shots + marking + penalties + positioning +
                 reactions + short_passing + shot_power + sliding_tackle + sprint_speed + stamina +
                 standing_tackle + strength + vision + volleys, data = train)

gam.m3 = gam(transformed_value ~ s(age) + nationality + potential + special + acceleration 
             + aggression + agility + balance + ball_control + composure + crossing + curve + 
                 dribbling + finishing + free_kick_accuracy + gk_diving + gk_handling + gk_kicking +
                 gk_positioning + gk_reflexes + heading_accuracy + interceptions +
                 jumping + long_passing + long_shots + marking + penalties + positioning +
                 s(reactions) + short_passing + shot_power + sliding_tackle + sprint_speed + 
                 stamina + standing_tackle + strength + vision + volleys, data = train)

gam.m4 = gam(transformed_value ~ s(age) + nationality + s(potential) + s(special) + acceleration 
             + aggression + agility + balance + ball_control + composure + crossing + curve + 
                 dribbling + finishing + s(free_kick_accuracy) + s(gk_diving) + gk_handling + gk_kicking +
                 s(gk_positioning) + s(gk_reflexes) + heading_accuracy + interceptions +
                 jumping + long_passing + long_shots + marking + penalties + positioning +
                 s(reactions) + short_passing + shot_power + sliding_tackle + sprint_speed + 
                 stamina + standing_tackle + strength + vision + volleys, data = train)

anova(gam.m1, gam.m2, gam.m3, gam.m4, test = "F")
```